### ISSUE TITLE
cross platform?

### ISSUE THREAD

**Issue by underdoeg** [toolbits/ofxWatchdog#1]
not really an issue but a question: Is this addon cross platform or does it use OS X only features?

**Comment by toolbits** [comment]
Hi, I think current version is compatible only with MacOS X. Because it uses POSIX functions, maybe it is compilable in Linux or in ARM-GCC. I don't check them yet. I'm glad that someone translates this for windows.

**Comment by underdoeg** [comment]
Depending on what POSIX standart you are using, it should be compatible with linux as well. I'll try it...

**Comment by schwittlick** [comment]
Did you eventually try it? I'm thinking about giving it a go, too. I'd be happy about hearing your experienece with it on linux.

**Comment by underdoeg** [comment]
No, I ended up using a simple shell script that ran the app in an endless loop...

**Comment by micuat** [comment]
Seems like not compatible with osx 10.6 either as `kProcessTransformToBackgroundApplication` only works with >=10.7 (ref: code in http://permalink.gmane.org/gmane.comp.lib.wxwidgets.devel/151832)

**Comment by toolbits** [comment]
Every one, now, I made ofxWatchdog supporting ubuntu linux 14.04 TLS. Also it supports MacOS X 10.10 Yosemite. Please check it.

**Comment by schwittlick** [comment]
This is great news, I'll test it asap. Cheers!

**Comment by stephanschulz** [comment]
nice addon !

would anyone know if this could run on a raspberry pi?
