### ISSUE TITLE
Run examples but got errors about "#pragma clang optimize push" and "#pragma clang optimize pop" 

### ISSUE THREAD

**Issue by wfdiao** [toolbits/ofxWatchdog#2]
![screen shot 2015-04-24 at 1 15 33 pm](https://cloud.githubusercontent.com/assets/5430172/7324385/0ab3cd56-ea84-11e4-9dac-5566161a8101.png)
Just download and run your example, got 3 errors about "#pragma clang optimize push","#pragma clang optimize "O0"" and "#pragma clang optimize pop" 
Can any one give me some suggestion?

MAC OSX 10.10.1  
OF: v0.8.4  
Xcode: Version 6.3 (6D570)

**Comment by toolbits** [comment]
Hi, I modified this error. It based on the specification of clang 3.6.
