### ISSUE TITLE
Urgent- need feedback on configuring

### ISSUE THREAD

**Issue by jBachalo** [toolbits/ofxWatchdog#3]
Hi
Thanks you for sharing with the community!
Couple questions regarding initializing.
1 What would be the purpose and result of setting the 3rd parmeter, 'use internal signal handler' to true?

2 If the last parameter 'print more log info', is set to true, is this log info printed to an external file, or?

Thanks in advance!

bach 44 at gmail dot com

**Comment by toolbits** [comment]
Hi, jBachalo

Here are some answers:
1 When you set this flag, ofxWatchdog installs some custom signal handler functions.
ofxWatchdog's handler catches SIGILL, SIGABRT, SIGFPE, SIGBUS, SIGSEGV signals.
When you use your own signal handlers, ofxWatchdog's signal handler may conflict with your handler.
This option controls this issue.

2 verbose option prints more information to std::cout and std::cerr.
So, if you want to print infos to a log file, you can redirect with pipe function.

thank you.

**Comment by toolbits** [comment]
closed
