### ISSUE TITLE
does it work with OF 0.9.0

### ISSUE THREAD

**Issue by antimodular** [toolbits/ofxWatchdog#4]
I tried it with OF0.9.0 and build a new project with projector Generator. The app on start up throws this many times in a row
`ofxWatchdog [parent] detects SIGSEGV.`

**Comment by TarGz** [comment]
I have the same issue, any update on this ?

**Comment by toolbits** [comment]
Hi, I tried to modify this error.
I used of 0.9.2 OS X.
The modification is changing boot process of application at main() function.
Please test latest version.
thank you.

**Comment by toolbits** [comment]
fixed
