### ISSUE TITLE
‘PATH_MAX’ was not declared

### ISSUE THREAD

**Issue by frauzufall** [toolbits/ofxWatchdog#5]
Hey, thank you for this addon, it looks really promising! 
I get this error though when compiling an example:

```
../../../addons/ofxWatchdog/src/ofxWatchdog.cpp: In static member function ‘static void ofxWatchdog::child()’:
../../../addons/ofxWatchdog/src/ofxWatchdog.cpp:313:15: error: ‘PATH_MAX’ was not declared in this scope
     char path[PATH_MAX];
```

Any hints what could be the problem? I am on Ubuntu 15.10 64bit.

**Comment by toolbits** [comment]
Hi, I think PATH_MAX is defined in <limits.h> on Linux.
But, I have not tested compiling my addon on Ubuntu 15.10.
If you can't find PATH_MAX on your environment, you can define PATH_MAX temporally as next:
#define PATH_MAX (4096)

Thank you.

**Comment by frauzufall** [comment]
the example is working now, thank you! :)

**Comment by toolbits** [comment]
I have merged your modification. Thank you for your help.
