### ISSUE TITLE
safely stop watchdog?

### ISSUE THREAD

**Issue by getarobo** [toolbits/ofxWatchdog#8]
Hey i was wondering how to stop watchdog to watch.

Thank you.

**Comment by toolbits** [comment]
Hi, do you want to stop watching temporarily?
If you want to stop it when exiting the application, you don't have to worry about it.
Using exit(int) or ofExit(int) functions causes you safety exiting from the ofxWatchdog.

**Comment by getarobo** [comment]
awesome, ofExit() worked fine!

**Comment by getarobo** [comment]
I exited out with ofExit(); 

ofapp did exit without any 
but still ofwatchdog caught SIGABRT
and reopened the app.

I wanted so if i exit with keypress. I dont want it to reopen.

**Comment by getarobo** [comment]
terminate called without an active exception
ofxWatchdog [parent] detects SIGABRT.

this what i get from terminal, when I tried to exit with ofExit().

**Comment by toolbits** [comment]
Thank you for your researching about this problem.
I'll try to find this problem and to fix it.

**Comment by getarobo** [comment]
thank you so much. let me know how i can help too.
fyi  my system is ubuntu 16.10 with of 0.9.8(github).

**Comment by laserpilot** [comment]
is there a workaround we could do with the existing functions in the addon to make it think it did a safe shutdown/graceful exit? I suspect something with linux is keeping it alive versus macOS

**Comment by getarobo** [comment]
I used  code below to stop ofxWatchDog reviving app. 
```
ofSystem("killall NAME_OF_THE_APP & killall NAME_OF_THE_APP");

```

**Comment by toolbits** [comment]
Hi, I tried to find the bug of your report, however, I could not get it.
I compiled latest ofxWatchdog addon on ubuntu linux 16.10 with of 0.9.8.

example_hangupRebootExample seems working fine.
example_hangupShutdownExample also worked fine in my environment.

Here is a terminal log...

administrator@ubuntu:\~/Documents/of_v0.9.8_linux64_release/addons/ofxWatchdog/example_hangupShutdownExample$ make run
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl rtaudio gl glu glew gtk+-3.0 
ofxWatchdog [parent] detects exit.
administrator@ubuntu:\~/Documents/of_v0.9.8_linux64_release/addons/ofxWatchdog/example_hangupShutdownExample$ make run
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl rtaudio gl glu glew gtk+-3.0 
ofxWatchdog [parent] detects SIGABRT.
../../../libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:169: recipe for target 'run' failed
make: *** [run] Error 1

When I exit app with ESC key, ofxWatchdog detects exit and safely shutdowns the app.
When I press 'A' key and make SIGABRT signal, ofxWatchdog detects SIGABRT and shutdowns the app with ::exit(1) function calling. So, "recipe for target 'run' failed" line is shown.

Can you send me some sample code containing the problem?

**Comment by toolbits** [comment]
And I also checked to use ofExit() and exit() function.
But, I couldn't find any bugs.

Your project contains using of some threads?
